feature: added creative energy hatches
IdealIndustrial/GT5Unofficial pull request #240
Opened 2022-09-26 18:48 UTC by KostyaKapitonov

2022-10-19 00:16 UTC, Pilad commented on src/main/java/gregtech/api/enums/ItemList.java
> +            DYE_ONLY_ITEMS = {Color_00, Color_01, Color_02, Color_03, Color_04, Color_05, Color_06, Color_07, Color_08, Color_09, Color_10, Color_11, Color_12, Color_13, Color_14, Color_15}, SPRAY_CA
Только МВ вписал тут, а остальные не нужно?

2022-11-03 04:27 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/enums/ItemList.java
> +            DYE_ONLY_ITEMS = {Color_00, Color_01, Color_02, Color_03, Color_04, Color_05, Color_06, Color_07, Color_08, Color_09, Color_10, Color_11, Color_12, Color_13, Color_14, Color_15}, SPRAY_CA
требует разъяснений как минимум )

2022-11-03 04:28 UTC, AndreySolodovnikov requested changes
строка с хетчами вызывает вопросы
почему именно Мв и почему только Мв

2022-11-03 08:28 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/enums/ItemList.java
> +            DYE_ONLY_ITEMS = {Color_00, Color_01, Color_02, Color_03, Color_04, Color_05, Color_06, Color_07, Color_08, Color_09, Color_10, Color_11, Color_12, Color_13, Color_14, Color_15}, SPRAY_CA
не помню уже - наверное даже МВ оттуда можно убрать - нам для креатива красить их не надо будет)
ну или остальные добавить конечно же можно

2022-11-03 09:46 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/enums/ItemList.java
> +            DYE_ONLY_ITEMS = {Color_00, Color_01, Color_02, Color_03, Color_04, Color_05, Color_06, Color_07, Color_08, Color_09, Color_10, Color_11, Color_12, Color_13, Color_14, Color_15}, SPRAY_CA
обнови ПР тогда

2022-11-03 09:51 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/enums/ItemList.java
> +            DYE_ONLY_ITEMS = {Color_00, Color_01, Color_02, Color_03, Color_04, Color_05, Color_06, Color_07, Color_08, Color_09, Color_10, Color_11, Color_12, Color_13, Color_14, Color_15}, SPRAY_CA
ок

2022-11-04 18:51 UTC, KostyaKapitonov commented
@AndreySolodovnikov  убрал мв из доступных к покраске

2022-11-05 11:38 UTC, merged