creative fluid loader upgrade and primitive pump fix
IdealIndustrial/GT5Unofficial pull request #247
Opened 2022-10-26 16:35 UTC by KostyaKapitonov

2022-11-03 04:07 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/covers/GT_Cover_CreativeWaterLoader.java
> +        }
catch Throwable вне контекста обработки ошибок это слишком

2022-11-03 04:07 UTC, AndreySolodovnikov requested changes
try catch надо убрать

2022-11-04 19:00 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/covers/GT_Cover_CreativeWaterLoader.java
> +        }
@AndreySolodovnikov  убрал

2022-11-05 11:36 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/covers/GT_Cover_CreativeWaterLoader.java
> +        }
надеюсь оно теперь не выкидывает ошибки наружу )

2022-11-05 11:36 UTC, merged

2022-11-05 14:28 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/covers/GT_Cover_CreativeWaterLoader.java
> +        }
@AndreySolodovnikov  нее, я во время разработки завернул т.к. падало - пока разбирался как это вообще сделать...
но потом забыл убрать, вернее просто не подумал, что его тут оставлять нежелательно