added 3 by 3 disassemble mode for HV wrench
IdealIndustrial/GT5Unofficial pull request #250
Opened 2022-10-30 14:34 UTC by KostyaKapitonov

2022-11-03 04:00 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tools/GT_Tool_Wrench_HV.java
> +
вот это дело - лишнее 
по умолчанию значение у НБТ - 0 - поэтому если деволтный мод сделать 0ем, а 3х3 1, то и вот этот кусок кода будет не нужен - и ключи скрафченные до обновы сразу получат режим работы по молчанию

2022-11-03 04:00 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/items/GT_MetaGenerated_Tool.java
> +                    mode = mode == 1 ? 2 : 1;
вот тут модулярная арифметика - самое то ) 
чтобы не городить нетипичные конструкции

2022-11-03 04:01 UTC, AndreySolodovnikov requested changes
в общем это надо поправить, сейчас старые HW ключи не будут переключать режимы

2022-11-05 09:38 UTC, KostyaKapitonov commented
@AndreySolodovnikov поправил

2022-11-05 11:32 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/items/GT_MetaGenerated_Tool.java
> +                }
ну теперь у нас локаль надо поддерживать 
так что тут так же как в ПРе на локализацию нужно 
```Player.addChatComponentMessage(new ChatComponentTranslation...```

2022-11-05 11:34 UTC, AndreySolodovnikov requested changes
локализацию докинь пожайста, в остальном - норм

2022-11-05 16:27 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/items/GT_MetaGenerated_Tool.java
> +                }
@AndreySolodovnikov  готово

2022-11-26 21:48 UTC, AndreySolodovnikov commented
хорошо 
правда на корректность - будем еще тестить

2022-11-26 21:49 UTC, merged