Primitive miner
IdealIndustrial/GT5Unofficial pull request #255
Opened 2022-11-26 17:42 UTC by KostyaKapitonov

1) added primitive mine digger
2) added primitive miner
3) added ability to use LV prospector to do cheap but lite ore scanning

2022-11-26 17:47 UTC, KostyaKapitonov commented
@AndreySolodovnikov  привет)
как появится возможность, глянь пожалуйста в приоритете этот ПР и прими, если ок
а если нет - напиши чё не так - переделаю.
щас под эти изменения хочу уже начать квесты пилить

2022-11-26 21:24 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/gui/GT_GUIContainer_PrimitiveMiner.java
> +    int[] dbg = new int[]{35,69,35,67};
вообще не ясно что это такое, название без сокращений и более понятное нужно

2022-11-26 21:24 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/gui/GT_GUIContainer_PrimitiveMiner.java
> +            if (mContainer.mSteam > 0) { // TODO
todo: что сделать ( не просто "fix bug")

2022-11-26 21:27 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +                }*/
надо писать почему закомментил, если больше не понадобится - сразу удалять и все, лишний техдолг

2022-11-26 21:28 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +    }
проверять на small руды можно по id блока, у них вроде <16k он

2022-11-26 21:28 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +    }
по внутреннему id который из TE вытащить можно 
детрав сканеры так делают например

2022-11-26 21:30 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
зачем тут данные страдания ? 
как минимум в гт уже есть код перемещения предметов, к тому же более общий 
сундук конечно хорошо, а что на счет ironChests ? MEInterface? или просто рандомный инвентарь из мода ? 
IInventory интерфейс в помощь в общем

2022-11-26 21:34 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        boolean isValid = true;
тут осторожно нужно быть, данный метод работает через всем известное место, 
на вид - все ок, но
обязательно нужно протестить работу с АЕ2 пилонами

2022-11-26 21:36 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        if(isAirWaterLava(aWorld.getBlock(te.getXCoord(), aY-1, te.getZCoord()))) { // checking a flor to be a block
тут лучше использовать соответствующий метод блока, сейчас оно наверняка факела на траву/ лианы/ лестницы / рельсы ставить будет

2022-11-26 21:45 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
упс, а этот код действительно лишний вообще - механику переделал и он уже не востребован даже в таком виде

2022-11-26 21:47 UTC, AndreySolodovnikov requested changes
есть пару спорных решений в общем, на корректность работы - не проверял

2022-11-26 21:47 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/enums/RelativeOffset.java
> +public enum RelativeOffset {
вроде в фордже есть подобный енум, ну ладно

2022-11-26 21:47 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
у этого класса и класса выше- тонна общего кода, нужно выносить общую базу, чтобы потом не мучиться

2022-11-26 21:47 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
и кстати, а зачем этим классам быть многоблоками ? не очень вижу логику пока что

2022-11-26 21:47 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tools/GT_Tool_Pickaxe.java
> +
а копипастить зачем ?  
isMinableBlock разве где-то переопределен ? 
если да - можно хотя бы вызов isMinableBlock перенаправить в canMineBlock раз уж он статический

2022-11-26 21:47 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tools/GT_Tool_Shovel.java
>      public ItemStack getBrokenItem(ItemStack aStack) {
аналогично

2022-11-26 21:47 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        if(isAirWaterLava(aWorld.getBlock(te.getXCoord(), aY-1, te.getZCoord()))) { // checking a flor to be a block
ээ, а это какой? знал бы  - юзал бы сразу изначально

2022-11-26 21:49 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
изначально брал за основу pile igniter - тот что для угольной ямы - он ведь с пространством тоже работает
на мой взгляд это был наиболее близкий мех который и взял за основу - а он мультиблок как оказалось

2022-11-26 21:50 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
мультиблок - тот кому требуется поддерживать свою структуру и проверять ее обновления, все остальные ими быть не должны ( pile igniter кстати тоже не должен быть мультиблоком, он поллингом проверяет а не "ивенты" слушает)

2022-11-26 21:51 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tools/GT_Tool_Pickaxe.java
> +
это уже тоже не нужно - пробовал новую механику которая в итоге не пригодилась - откачу

2022-11-26 21:51 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tools/GT_Tool_Shovel.java
>      public ItemStack getBrokenItem(ItemStack aStack) {
тоже откачу

2022-11-26 22:42 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
@AndreySolodovnikov  вернее pushToChest - не нужен
а pushToOutputSlots - пользуюсь.

2022-11-26 22:44 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
pushToOutputSlots - замены не нашёл, если знаешь какая тут подойдёт - напиши плиз, подправлю...
а так - оно работает и может быть переиспользовано.
из тех методов что я видел - там из одного инвентаря перемещают в другой, а у меня задача из ниоткуда запихнуть в слоты аутпута которых много, подобного не нашёл метода...

2022-11-26 22:46 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        boolean isValid = true;
вот тут вообще не понял о чём ты,
если ты про метод validate - то этом мой кастомный метод, я его не переопределял, просто название подходящее. если название метода не нравится могу переименовать на другое но со схожим смыслом...

2022-11-26 22:47 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
ну вот - неудачно взял механизм за основу, думая, что он будет хорошим примером(
это критично? стоит переписать?

2022-11-26 22:48 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        boolean isValid = true;
доперло ) 
да у TileEntity из кубача такой же метод есть, испугался когда увидел ))

2022-11-26 22:49 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tools/GT_Tool_Pickaxe.java
> +
а вообще там бысл смысл в том чтоб метод был static - удобнее юзать чтоб было, не создавая каждый раз новый инстанс класса

2022-11-26 22:49 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tools/GT_Tool_Pickaxe.java
> +
в любом случае уже не юзается - удаляю.

2022-11-26 22:50 UTC, AndreySolodovnikov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
ну раз pushToChest  не нужен - удаляй его, второй метод - ок, учитывая что у тебя специфичный юзкейс 
(можно конечно обернуть вход в подобие инвентаря и как раз заиспользовать те методы, но раз уж есть рабочая версия - лишняя морока)

2022-11-26 22:59 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveMineDigger.java
> +        if(isAirWaterLava(aWorld.getBlock(te.getXCoord(), aY-1, te.getZCoord()))) { // checking a flor to be a block
разобрался - сделал

2022-11-26 22:59 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
ну это создает проблемы дополнительные 
в плане это же не мультиблок все таки...
в любом случае требуется вынести общую базу, а мультиблок легко заменяется на одноблок так то, можешь глянуть майнеры и помпы одноблочные как пример.
Общую базу вынести нужно 100%, я когда арееи писал - мне такого никто не сказал, а потом мы с ними намучились...

2022-11-26 23:01 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
ок так и сделаю - pushToChest  удалил

2022-11-26 23:02 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/gui/GT_GUIContainer_PrimitiveMiner.java
> +    int[] dbg = new int[]{35,69,35,67};
готово

2022-11-26 23:03 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/gui/GT_GUIContainer_PrimitiveMiner.java
> +            if (mContainer.mSteam > 0) { // TODO
там всё норм - просто коммент забыл убрать
оставлял для себя чтоб, не забыть на чём остановился)
удалил коммент

2022-11-26 23:03 UTC, KostyaKapitonov commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +                }*/
да, больше не нужен - удалил

2022-11-30 21:26 UTC, KostyaKapitonov commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PrimitiveSmallOreMiner.java
> +public class GT_MetaTileEntity_PrimitiveSmallOreMiner extends GT_MetaTileEntity_MultiBlockBase {
@AndreySolodovnikov  готово))
задолбался я знатно конечно, зато теперь код (по паренту и двум наследуемым классам) - хоть в резюме вставляй)
причесал его по максимум, на мой взгляд)

2024-05-10 21:47 UTC, WiseProjects commented
Implemented in other pr

2024-05-10 21:47 UTC, closed without merging