new pumps
IdealIndustrial/GT5Unofficial pull request #84
Opened 2020-04-11 20:59 UTC by AndreySolodovnikov

переписал помпы, теперь аналогичны майнерам

2020-04-11 21:00 UTC, AndreySolodovnikov commented
сюда случайно попал коммит на новый баланс статов нефтекачек, но это тоже нужно, так что не думаю что проблема

2020-04-14 09:21 UTC, SaloEater requested changes
Приношу свои извинения, но очень сильно захотелось так сделать.

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +        if (aBaseMetaTileEntity.isServerSide()) {
Сделать return, если тикает у клиента.
```suggestion
        if (this.isClientSide(aBaseMetaTileEntity)) {
             mMaxProgresstime = 0;
             return;
        }
        ...
        
        private bool isClientSide(IGregTechTileEntity aBaseMetaTileEntity)
        {
            return !aBaseMetaTileEntity.isServerSide();
        }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (aBaseMetaTileEntity.isAllowedToWork() && aBaseMetaTileEntity.isUniversalEnergyStored(ENERGY[mTier] * (SPEED[mTier] - mProgresstime)) && hasFreeSpace()) {
Было бы круто вынести в отдельный метод проверки связанные с TE
```suggestion
            if (
                isTEAllowedToWorkAndStoredEnoughEnergy(aBaseMetaTileEntity)
                && hasFreeSpace()
            ) {
            
            ...
            private bool isTEAllowedToWorkAndStoredEnoughEnergy(IGregTechTileEntity aBaseMetaTileEntity)
            {
                return aBaseMetaTileEntity.isAllowedToWork() && aBaseMetaTileEntity.isUniversalEnergyStored(ENERGY[mTier] * (SPEED[mTier] - mProgresstime));
            }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                if (waitMiningPipe) {
Можно вынести весь цикл в метод и, возможно, избавиться от флага waitMiningPipe.
```suggestion
                    if (waitMiningPipe && noMiningPipesInInput()) {
                        mMaxProgresstime = 0;
                        return;
                    }
                    ...
                    private bool noMiningPipesInInput()
                    {
                        for (int i = 0; i < mInputSlotCount; i++) {
                            ItemStack s = getInputAt(i);
                            if (s != null && s.getItem() == MINING_PIPE.getItem() && s.stackSize > 0) {
                                waitMiningPipe = false;
                                return false;
                            }
                        }
                        return true;
                    }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilDrillBase.java
> +        this.mMaxProgresstime = (workState == STATE_AT_BOTTOM ? 320 : 80) / (1 << tier);
Не может ли быть такого, что эти значения уже вынесены в константы?
В любом случае их лучше вынести в константы.

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (mProgresstime == SPEED[mTier] - 1) {
Выражение SPEED[mTier] - 1 стоит тоже вынести, но его смысл для меня непонятен, поэтому на ваше усмотрение.
```suggestion
            if (mProgresstime != SPEED[mTier] - 1) {
                return;
            }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                if (isPickingPipes) {
После предыдущего ченжа будет логичнее избавиться от return'a и превратить конструкцию в 
```suggestion
                if (isPickingPipes) {
                
                } else {
                
                }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                if (drillY == 0) {
Выражение _drillY == 0 || drillZ > RADIUS[mTier]_ тоже стоит вынести в отдельную функцию, но название для меня вообще не очевидно, поэтому на ваше усмотрение.
```suggestion
                if (drillY == 0 || drillZ > RADIUS[mTier]) {
                    moveOneDown(aBaseMetaTileEntity);
                } else {
                    while (drillZ <= RADIUS[mTier]) {
                        while (drillX <= RADIUS[mTier]) {
                            if(workBlock(aBaseMetaTileEntity))
                              return;
                           drillX++;
                        }
                        drillX = -RADIUS[mTier];
                        drillZ++;
                    }
                }                
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                    } else if (aBaseMetaTileEntity.getBlockOffset(0, drillY, 0) == MINING_PIPE_TIP_BLOCK || aBaseMetaTileEntity.getBlockOffset(0, drillY, 0) == MINING_PIPE_BLOCK) {
```suggestion
                    } else if (isPipeBelowTEOnOffset(drillY) {
                    ...
                    private bool isPipeBelowTEOnOffset(int offset)
                    {
                       return aBaseMetaTileEntity.getBlockOffset(0, offset, 0) == MINING_PIPE_TIP_BLOCK 
                       || aBaseMetaTileEntity.getBlockOffset(0, offset, 0) == MINING_PIPE_BLOCK;
                    }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +            if (association != null && association.mPrefix.toString().startsWith("ore")) {
Немного странно, что _"ore"_ за столько лет не вынесли в константу )
```suggestion
            if (doesBlockHaveOreAssociation(block, blockMeta)) {
            ...
            private bool doesBlockHaveOreAssociation(Block block, int blockMeta)
            {
                ItemData association = GT_OreDictUnificator.getAssociation(new ItemStack(block, 1, blockMeta));
                return association != null && association.mPrefix.toString().startsWith("ore");
            }
```

2020-04-14 09:21 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +            if (tTileEntity != null && tTileEntity instanceof GT_TileEntity_Ores && ((GT_TileEntity_Ores) tTileEntity).mNatural) {
```suggestion
            if (tTileEntity != null && isNaturalOre(tTileEntity )) {
            
            ...
            private bool isNaturalOre(TileEntity tTileEntity)
            {
                return tTileEntity instanceof GT_TileEntity_Ores 
                    && ((GT_TileEntity_Ores) tTileEntity).mNatural;
            }
```

2020-04-14 12:35 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (aBaseMetaTileEntity.isAllowedToWork() && aBaseMetaTileEntity.isUniversalEnergyStored(ENERGY[mTier] * (SPEED[mTier] - mProgresstime)) && hasFreeSpace()) {
нет ни малейшего смысла создавать функции которые будут использованы ровно 1 раз, функции нужны для упрощения понимания или для уменьшения количества кода, тут имхо ни того, ни другого

2020-04-14 12:38 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (mProgresstime == SPEED[mTier] - 1) {
это самый банальный счетчик тиков, если поставить =! то будет работать каждый тик за исключением заданного значения => неверная работа

2020-04-14 12:40 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                if (drillY == 0) {
эта проверка совершенно лишняя, помпа не может добывать жидкости на том же уровне на котором находится контроллер

2020-04-14 12:40 UTC, AndreySolodovnikov commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +            if (association != null && association.mPrefix.toString().startsWith("ore")) {
а смысл констранты из 3х букв? думаешь это может изменится в будущем ?

2020-04-14 13:18 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (aBaseMetaTileEntity.isAllowedToWork() && aBaseMetaTileEntity.isUniversalEnergyStored(ENERGY[mTier] * (SPEED[mTier] - mProgresstime)) && hasFreeSpace()) {
К сожалению, с этой стороны есть только мое имхо по которому и я предложил данное изменение.

2020-04-14 13:22 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +            if (mProgresstime == SPEED[mTier] - 1) {
Обращаю внимание на 68 строку в ченже.

2020-04-14 13:26 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_BasicDrillerBase.java
> +                if (drillY == 0) {
Объединил оригинальные 80 и 84 строки, чтобы избавиться от return'ов.

2020-04-14 13:28 UTC, SaloEater commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +            if (association != null && association.mPrefix.toString().startsWith("ore")) {
Это скорее nit, просто выразил удивление, что нет стандарта для наименований.

2020-05-06 17:12 UTC, merged